<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $cities = [
            ['id' => 1101, 'province_id' => 11, 'title' => 'KABUPATEN SIMEULUE'],
            ['id' => 1102, 'province_id' => 11, 'title' => 'KABUPATEN ACEH SINGKIL'],
            ['id' => 1103, 'province_id' => 11, 'title' => 'KABUPATEN ACEH SELATAN'],
            ['id' => 1104, 'province_id' => 11, 'title' => 'KABUPATEN ACEH TENGGARA'],
            ['id' => 1105, 'province_id' => 11, 'title' => 'KABUPATEN ACEH TIMUR'],
            ['id' => 1106, 'province_id' => 11, 'title' => 'KABUPATEN ACEH TENGAH'],
            ['id' => 1107, 'province_id' => 11, 'title' => 'KABUPATEN ACEH BARAT'],
            ['id' => 1108, 'province_id' => 11, 'title' => 'KABUPATEN ACEH BESAR'],
            ['id' => 1109, 'province_id' => 11, 'title' => 'KABUPATEN PIDIE'],
            ['id' => 1110, 'province_id' => 11, 'title' => 'KABUPATEN BIREUEN'],
            ['id' => 1111, 'province_id' => 11, 'title' => 'KABUPATEN ACEH UTARA'],
            ['id' => 1112, 'province_id' => 11, 'title' => 'KABUPATEN ACEH BARAT DAYA'],
            ['id' => 1113, 'province_id' => 11, 'title' => 'KABUPATEN GAYO LUES'],
            ['id' => 1114, 'province_id' => 11, 'title' => 'KABUPATEN ACEH TAMIANG'],
            ['id' => 1115, 'province_id' => 11, 'title' => 'KABUPATEN NAGAN RAYA'],
            ['id' => 1116, 'province_id' => 11, 'title' => 'KABUPATEN ACEH JAYA'],
            ['id' => 1117, 'province_id' => 11, 'title' => 'KABUPATEN BENER MERIAH'],
            ['id' => 1118, 'province_id' => 11, 'title' => 'KABUPATEN PIDIE JAYA'],
            ['id' => 1171, 'province_id' => 11, 'title' => 'KOTA BANDA ACEH'],
            ['id' => 1172, 'province_id' => 11, 'title' => 'KOTA SABANG'],
            ['id' => 1173, 'province_id' => 11, 'title' => 'KOTA LANGSA'],
            ['id' => 1174, 'province_id' => 11, 'title' => 'KOTA LHOKSEUMAWE'],
            ['id' => 1175, 'province_id' => 11, 'title' => 'KOTA SUBULUSSALAM'],
            ['id' => 1201, 'province_id' => 12, 'title' => 'KABUPATEN NIAS'],
            ['id' => 1202, 'province_id' => 12, 'title' => 'KABUPATEN MANDAILING NATAL'],
            ['id' => 1203, 'province_id' => 12, 'title' => 'KABUPATEN TAPANULI SELATAN'],
            ['id' => 1204, 'province_id' => 12, 'title' => 'KABUPATEN TAPANULI TENGAH'],
            ['id' => 1205, 'province_id' => 12, 'title' => 'KABUPATEN TAPANULI UTARA'],
            ['id' => 1206, 'province_id' => 12, 'title' => 'KABUPATEN TOBA SAMOSIR'],
            ['id' => 1207, 'province_id' => 12, 'title' => 'KABUPATEN LABUHAN BATU'],
            ['id' => 1208, 'province_id' => 12, 'title' => 'KABUPATEN ASAHAN'],
            ['id' => 1209, 'province_id' => 12, 'title' => 'KABUPATEN SIMALUNGUN'],
            ['id' => 1210, 'province_id' => 12, 'title' => 'KABUPATEN DAIRI'],
            ['id' => 1211, 'province_id' => 12, 'title' => 'KABUPATEN KARO'],
            ['id' => 1212, 'province_id' => 12, 'title' => 'KABUPATEN DELI SERDANG'],
            ['id' => 1213, 'province_id' => 12, 'title' => 'KABUPATEN LANGKAT'],
            ['id' => 1214, 'province_id' => 12, 'title' => 'KABUPATEN NIAS SELATAN'],
            ['id' => 1215, 'province_id' => 12, 'title' => 'KABUPATEN HUMBANG HASUNDUTAN'],
            ['id' => 1216, 'province_id' => 12, 'title' => 'KABUPATEN PAKPAK BHARAT'],
            ['id' => 1217, 'province_id' => 12, 'title' => 'KABUPATEN SAMOSIR'],
            ['id' => 1218, 'province_id' => 12, 'title' => 'KABUPATEN SERDANG BEDAGAI'],
            ['id' => 1219, 'province_id' => 12, 'title' => 'KABUPATEN BATU BARA'],
            ['id' => 1220, 'province_id' => 12, 'title' => 'KABUPATEN PADANG LAWAS UTARA'],
            ['id' => 1221, 'province_id' => 12, 'title' => 'KABUPATEN PADANG LAWAS'],
            ['id' => 1222, 'province_id' => 12, 'title' => 'KABUPATEN LABUHAN BATU SELATAN'],
            ['id' => 1223, 'province_id' => 12, 'title' => 'KABUPATEN LABUHAN BATU UTARA'],
            ['id' => 1224, 'province_id' => 12, 'title' => 'KABUPATEN NIAS UTARA'],
            ['id' => 1225, 'province_id' => 12, 'title' => 'KABUPATEN NIAS BARAT'],
            ['id' => 1271, 'province_id' => 12, 'title' => 'KOTA SIBOLGA'],
            ['id' => 1272, 'province_id' => 12, 'title' => 'KOTA TANJUNG BALAI'],
            ['id' => 1273, 'province_id' => 12, 'title' => 'KOTA PEMATANG SIANTAR'],
            ['id' => 1274, 'province_id' => 12, 'title' => 'KOTA TEBING TINGGI'],
            ['id' => 1275, 'province_id' => 12, 'title' => 'KOTA MEDAN'],
            ['id' => 1276, 'province_id' => 12, 'title' => 'KOTA BINJAI'],
            ['id' => 1277, 'province_id' => 12, 'title' => 'KOTA PADANG SIDEMPUAN'],
            ['id' => 1278, 'province_id' => 12, 'title' => 'KOTA GUNUNGSITOLI'],
            ['id' => 1301, 'province_id' => 13, 'title' => 'KABUPATEN KEPULAUAN MENTAWAI'],
            ['id' => 1302, 'province_id' => 13, 'title' => 'KABUPATEN PESISIR SELATAN'],
            ['id' => 1303, 'province_id' => 13, 'title' => 'KABUPATEN SOLOK'],
            ['id' => 1304, 'province_id' => 13, 'title' => 'KABUPATEN SIJUNJUNG'],
            ['id' => 1305, 'province_id' => 13, 'title' => 'KABUPATEN TANAH DATAR'],
            ['id' => 1306, 'province_id' => 13, 'title' => 'KABUPATEN PADANG PARIAMAN'],
            ['id' => 1307, 'province_id' => 13, 'title' => 'KABUPATEN AGAM'],
            ['id' => 1308, 'province_id' => 13, 'title' => 'KABUPATEN LIMA PULUH KOTA'],
            ['id' => 1309, 'province_id' => 13, 'title' => 'KABUPATEN PASAMAN'],
            ['id' => 1310, 'province_id' => 13, 'title' => 'KABUPATEN SOLOK SELATAN'],
            ['id' => 1311, 'province_id' => 13, 'title' => 'KABUPATEN DHARMASRAYA'],
            ['id' => 1312, 'province_id' => 13, 'title' => 'KABUPATEN PASAMAN BARAT'],
            ['id' => 1371, 'province_id' => 13, 'title' => 'KOTA PADANG'],
            ['id' => 1372, 'province_id' => 13, 'title' => 'KOTA SOLOK'],
            ['id' => 1373, 'province_id' => 13, 'title' => 'KOTA SAWAH LUNTO'],
            ['id' => 1374, 'province_id' => 13, 'title' => 'KOTA PADANG PANJANG'],
            ['id' => 1375, 'province_id' => 13, 'title' => 'KOTA BUKITTINGGI'],
            ['id' => 1376, 'province_id' => 13, 'title' => 'KOTA PAYAKUMBUH'],
            ['id' => 1377, 'province_id' => 13, 'title' => 'KOTA PARIAMAN'],
            ['id' => 1401, 'province_id' => 14, 'title' => 'KABUPATEN KUANTAN SINGINGI'],
            ['id' => 1402, 'province_id' => 14, 'title' => 'KABUPATEN INDRAGIRI HULU'],
            ['id' => 1403, 'province_id' => 14, 'title' => 'KABUPATEN INDRAGIRI HILIR'],
            ['id' => 1404, 'province_id' => 14, 'title' => 'KABUPATEN PELALAWAN'],
            ['id' => 1405, 'province_id' => 14, 'title' => 'KABUPATEN SIAK'],
            ['id' => 1406, 'province_id' => 14, 'title' => 'KABUPATEN KAMPAR'],
            ['id' => 1407, 'province_id' => 14, 'title' => 'KABUPATEN ROKAN HULU'],
            ['id' => 1408, 'province_id' => 14, 'title' => 'KABUPATEN BENGKALIS'],
            ['id' => 1409, 'province_id' => 14, 'title' => 'KABUPATEN ROKAN HILIR'],
            ['id' => 1410, 'province_id' => 14, 'title' => 'KABUPATEN KEPULAUAN MERANTI'],
            ['id' => 1471, 'province_id' => 14, 'title' => 'KOTA PEKANBARU'],
            ['id' => 1473, 'province_id' => 14, 'title' => 'KOTA DUMAI'],
            ['id' => 1501, 'province_id' => 15, 'title' => 'KABUPATEN KERINCI'],
            ['id' => 1502, 'province_id' => 15, 'title' => 'KABUPATEN MERANGIN'],
            ['id' => 1503, 'province_id' => 15, 'title' => 'KABUPATEN SAROLANGUN'],
            ['id' => 1504, 'province_id' => 15, 'title' => 'KABUPATEN BATANG HARI'],
            ['id' => 1505, 'province_id' => 15, 'title' => 'KABUPATEN MUARO JAMBI'],
            ['id' => 1506, 'province_id' => 15, 'title' => 'KABUPATEN TANJUNG JABUNG TIMUR'],
            ['id' => 1507, 'province_id' => 15, 'title' => 'KABUPATEN TANJUNG JABUNG BARAT'],
            ['id' => 1508, 'province_id' => 15, 'title' => 'KABUPATEN TEBO'],
            ['id' => 1509, 'province_id' => 15, 'title' => 'KABUPATEN BUNGO'],
            ['id' => 1571, 'province_id' => 15, 'title' => 'KOTA JAMBI'],
            ['id' => 1572, 'province_id' => 15, 'title' => 'KOTA SUNGAI PENUH'],
            ['id' => 1601, 'province_id' => 16, 'title' => 'KABUPATEN OGAN KOMERING ULU'],
            ['id' => 1602, 'province_id' => 16, 'title' => 'KABUPATEN OGAN KOMERING ILIR'],
            ['id' => 1603, 'province_id' => 16, 'title' => 'KABUPATEN MUARA ENIM'],
            ['id' => 1604, 'province_id' => 16, 'title' => 'KABUPATEN LAHAT'],
            ['id' => 1605, 'province_id' => 16, 'title' => 'KABUPATEN MUSI RAWAS'],
            ['id' => 1606, 'province_id' => 16, 'title' => 'KABUPATEN MUSI BANYU ASIN'],
            ['id' => 1607, 'province_id' => 16, 'title' => 'KABUPATEN BANYU ASIN'],
            ['id' => 1608, 'province_id' => 16, 'title' => 'KABUPATEN OGAN KOMERING ULU SELATAN'],
            ['id' => 1609, 'province_id' => 16, 'title' => 'KABUPATEN OGAN KOMERING ULU TIMUR'],
            ['id' => 1610, 'province_id' => 16, 'title' => 'KABUPATEN OGAN ILIR'],
            ['id' => 1611, 'province_id' => 16, 'title' => 'KABUPATEN EMPAT LAWANG'],
            ['id' => 1612, 'province_id' => 16, 'title' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'],
            ['id' => 1613, 'province_id' => 16, 'title' => 'KABUPATEN MUSI RAWAS UTARA'],
            ['id' => 1671, 'province_id' => 16, 'title' => 'KOTA PALEMBANG'],
            ['id' => 1672, 'province_id' => 16, 'title' => 'KOTA PRABUMULIH'],
            ['id' => 1673, 'province_id' => 16, 'title' => 'KOTA PAGAR ALAM'],
            ['id' => 1674, 'province_id' => 16, 'title' => 'KOTA LUBUK LINGGAU'],
            ['id' => 1701, 'province_id' => 17, 'title' => 'KABUPATEN BENGKULU SELATAN'],
            ['id' => 1702, 'province_id' => 17, 'title' => 'KABUPATEN REJANG LEBONG'],
            ['id' => 1703, 'province_id' => 17, 'title' => 'KABUPATEN BENGKULU UTARA'],
            ['id' => 1704, 'province_id' => 17, 'title' => 'KABUPATEN KAUR'],
            ['id' => 1705, 'province_id' => 17, 'title' => 'KABUPATEN SELUMA'],
            ['id' => 1706, 'province_id' => 17, 'title' => 'KABUPATEN MUKOMUKO'],
            ['id' => 1707, 'province_id' => 17, 'title' => 'KABUPATEN LEBONG'],
            ['id' => 1708, 'province_id' => 17, 'title' => 'KABUPATEN KEPAHIANG'],
            ['id' => 1709, 'province_id' => 17, 'title' => 'KABUPATEN BENGKULU TENGAH'],
            ['id' => 1771, 'province_id' => 17, 'title' => 'KOTA BENGKULU'],
            ['id' => 1801, 'province_id' => 18, 'title' => 'KABUPATEN LAMPUNG BARAT'],
            ['id' => 1802, 'province_id' => 18, 'title' => 'KABUPATEN TANGGAMUS'],
            ['id' => 1803, 'province_id' => 18, 'title' => 'KABUPATEN LAMPUNG SELATAN'],
            ['id' => 1804, 'province_id' => 18, 'title' => 'KABUPATEN LAMPUNG TIMUR'],
            ['id' => 1805, 'province_id' => 18, 'title' => 'KABUPATEN LAMPUNG TENGAH'],
            ['id' => 1806, 'province_id' => 18, 'title' => 'KABUPATEN LAMPUNG UTARA'],
            ['id' => 1807, 'province_id' => 18, 'title' => 'KABUPATEN WAY KANAN'],
            ['id' => 1808, 'province_id' => 18, 'title' => 'KABUPATEN TULANGBAWANG'],
            ['id' => 1809, 'province_id' => 18, 'title' => 'KABUPATEN PESAWARAN'],
            ['id' => 1810, 'province_id' => 18, 'title' => 'KABUPATEN PRINGSEWU'],
            ['id' => 1811, 'province_id' => 18, 'title' => 'KABUPATEN MESUJI'],
            ['id' => 1812, 'province_id' => 18, 'title' => 'KABUPATEN TULANG BAWANG BARAT'],
            ['id' => 1813, 'province_id' => 18, 'title' => 'KABUPATEN PESISIR BARAT'],
            ['id' => 1871, 'province_id' => 18, 'title' => 'KOTA BANDAR LAMPUNG'],
            ['id' => 1872, 'province_id' => 18, 'title' => 'KOTA METRO'],
            ['id' => 1901, 'province_id' => 19, 'title' => 'KABUPATEN BANGKA'],
            ['id' => 1902, 'province_id' => 19, 'title' => 'KABUPATEN BELITUNG'],
            ['id' => 1903, 'province_id' => 19, 'title' => 'KABUPATEN BANGKA BARAT'],
            ['id' => 1904, 'province_id' => 19, 'title' => 'KABUPATEN BANGKA TENGAH'],
            ['id' => 1905, 'province_id' => 19, 'title' => 'KABUPATEN BANGKA SELATAN'],
            ['id' => 1906, 'province_id' => 19, 'title' => 'KABUPATEN BELITUNG TIMUR'],
            ['id' => 1971, 'province_id' => 19, 'title' => 'KOTA PANGKAL PINANG'],
            ['id' => 2101, 'province_id' => 21, 'title' => 'KABUPATEN KARIMUN'],
            ['id' => 2102, 'province_id' => 21, 'title' => 'KABUPATEN BINTAN'],
            ['id' => 2103, 'province_id' => 21, 'title' => 'KABUPATEN NATUNA'],
            ['id' => 2104, 'province_id' => 21, 'title' => 'KABUPATEN LINGGA'],
            ['id' => 2105, 'province_id' => 21, 'title' => 'KABUPATEN KEPULAUAN ANAMBAS'],
            ['id' => 2171, 'province_id' => 21, 'title' => 'KOTA BATAM'],
            ['id' => 2172, 'province_id' => 21, 'title' => 'KOTA TANJUNG PINANG'],
            ['id' => 3101, 'province_id' => 31, 'title' => 'KABUPATEN KEPULAUAN SERIBU'],
            ['id' => 3171, 'province_id' => 31, 'title' => 'KOTA JAKARTA SELATAN'],
            ['id' => 3172, 'province_id' => 31, 'title' => 'KOTA JAKARTA TIMUR'],
            ['id' => 3173, 'province_id' => 31, 'title' => 'KOTA JAKARTA PUSAT'],
            ['id' => 3174, 'province_id' => 31, 'title' => 'KOTA JAKARTA BARAT'],
            ['id' => 3175, 'province_id' => 31, 'title' => 'KOTA JAKARTA UTARA'],
            ['id' => 3201, 'province_id' => 32, 'title' => 'KABUPATEN BOGOR'],
            ['id' => 3202, 'province_id' => 32, 'title' => 'KABUPATEN SUKABUMI'],
            ['id' => 3203, 'province_id' => 32, 'title' => 'KABUPATEN CIANJUR'],
            ['id' => 3204, 'province_id' => 32, 'title' => 'KABUPATEN BANDUNG'],
            ['id' => 3205, 'province_id' => 32, 'title' => 'KABUPATEN GARUT'],
            ['id' => 3206, 'province_id' => 32, 'title' => 'KABUPATEN TASIKMALAYA'],
            ['id' => 3207, 'province_id' => 32, 'title' => 'KABUPATEN CIAMIS'],
            ['id' => 3208, 'province_id' => 32, 'title' => 'KABUPATEN KUNINGAN'],
            ['id' => 3209, 'province_id' => 32, 'title' => 'KABUPATEN CIREBON'],
            ['id' => 3210, 'province_id' => 32, 'title' => 'KABUPATEN MAJALENGKA'],
            ['id' => 3211, 'province_id' => 32, 'title' => 'KABUPATEN SUMEDANG'],
            ['id' => 3212, 'province_id' => 32, 'title' => 'KABUPATEN INDRAMAYU'],
            ['id' => 3213, 'province_id' => 32, 'title' => 'KABUPATEN SUBANG'],
            ['id' => 3214, 'province_id' => 32, 'title' => 'KABUPATEN PURWAKARTA'],
            ['id' => 3215, 'province_id' => 32, 'title' => 'KABUPATEN KARAWANG'],
            ['id' => 3216, 'province_id' => 32, 'title' => 'KABUPATEN BEKASI'],
            ['id' => 3217, 'province_id' => 32, 'title' => 'KABUPATEN BANDUNG BARAT'],
            ['id' => 3218, 'province_id' => 32, 'title' => 'KABUPATEN PANGANDARAN'],
            ['id' => 3271, 'province_id' => 32, 'title' => 'KOTA BOGOR'],
            ['id' => 3272, 'province_id' => 32, 'title' => 'KOTA SUKABUMI'],
            ['id' => 3273, 'province_id' => 32, 'title' => 'KOTA BANDUNG'],
            ['id' => 3274, 'province_id' => 32, 'title' => 'KOTA CIREBON'],
            ['id' => 3275, 'province_id' => 32, 'title' => 'KOTA BEKASI'],
            ['id' => 3276, 'province_id' => 32, 'title' => 'KOTA DEPOK'],
            ['id' => 3277, 'province_id' => 32, 'title' => 'KOTA CIMAHI'],
            ['id' => 3278, 'province_id' => 32, 'title' => 'KOTA TASIKMALAYA'],
            ['id' => 3279, 'province_id' => 32, 'title' => 'KOTA BANJAR'],
            ['id' => 3301, 'province_id' => 33, 'title' => 'KABUPATEN CILACAP'],
            ['id' => 3302, 'province_id' => 33, 'title' => 'KABUPATEN BANYUMAS'],
            ['id' => 3303, 'province_id' => 33, 'title' => 'KABUPATEN PURBALINGGA'],
            ['id' => 3304, 'province_id' => 33, 'title' => 'KABUPATEN BANJARNEGARA'],
            ['id' => 3305, 'province_id' => 33, 'title' => 'KABUPATEN KEBUMEN'],
            ['id' => 3306, 'province_id' => 33, 'title' => 'KABUPATEN PURWOREJO'],
            ['id' => 3307, 'province_id' => 33, 'title' => 'KABUPATEN WONOSOBO'],
            ['id' => 3308, 'province_id' => 33, 'title' => 'KABUPATEN MAGELANG'],
            ['id' => 3309, 'province_id' => 33, 'title' => 'KABUPATEN BOYOLALI'],
            ['id' => 3310, 'province_id' => 33, 'title' => 'KABUPATEN KLATEN'],
            ['id' => 3311, 'province_id' => 33, 'title' => 'KABUPATEN SUKOHARJO'],
            ['id' => 3312, 'province_id' => 33, 'title' => 'KABUPATEN WONOGIRI'],
            ['id' => 3313, 'province_id' => 33, 'title' => 'KABUPATEN KARANGANYAR'],
            ['id' => 3314, 'province_id' => 33, 'title' => 'KABUPATEN SRAGEN'],
            ['id' => 3315, 'province_id' => 33, 'title' => 'KABUPATEN GROBOGAN'],
            ['id' => 3316, 'province_id' => 33, 'title' => 'KABUPATEN BLORA'],
            ['id' => 3317, 'province_id' => 33, 'title' => 'KABUPATEN REMBANG'],
            ['id' => 3318, 'province_id' => 33, 'title' => 'KABUPATEN PATI'],
            ['id' => 3319, 'province_id' => 33, 'title' => 'KABUPATEN KUDUS'],
            ['id' => 3320, 'province_id' => 33, 'title' => 'KABUPATEN JEPARA'],
            ['id' => 3321, 'province_id' => 33, 'title' => 'KABUPATEN DEMAK'],
            ['id' => 3322, 'province_id' => 33, 'title' => 'KABUPATEN SEMARANG'],
            ['id' => 3323, 'province_id' => 33, 'title' => 'KABUPATEN TEMANGGUNG'],
            ['id' => 3324, 'province_id' => 33, 'title' => 'KABUPATEN KENDAL'],
            ['id' => 3325, 'province_id' => 33, 'title' => 'KABUPATEN BATANG'],
            ['id' => 3326, 'province_id' => 33, 'title' => 'KABUPATEN PEKALONGAN'],
            ['id' => 3327, 'province_id' => 33, 'title' => 'KABUPATEN PEMALANG'],
            ['id' => 3328, 'province_id' => 33, 'title' => 'KABUPATEN TEGAL'],
            ['id' => 3329, 'province_id' => 33, 'title' => 'KABUPATEN BREBES'],
            ['id' => 3371, 'province_id' => 33, 'title' => 'KOTA MAGELANG'],
            ['id' => 3372, 'province_id' => 33, 'title' => 'KOTA SURAKARTA'],
            ['id' => 3373, 'province_id' => 33, 'title' => 'KOTA SALATIGA'],
            ['id' => 3374, 'province_id' => 33, 'title' => 'KOTA SEMARANG'],
            ['id' => 3375, 'province_id' => 33, 'title' => 'KOTA PEKALONGAN'],
            ['id' => 3376, 'province_id' => 33, 'title' => 'KOTA TEGAL'],
            ['id' => 3401, 'province_id' => 34, 'title' => 'KABUPATEN KULON PROGO'],
            ['id' => 3402, 'province_id' => 34, 'title' => 'KABUPATEN BANTUL'],
            ['id' => 3403, 'province_id' => 34, 'title' => 'KABUPATEN GUNUNG KIDUL'],
            ['id' => 3404, 'province_id' => 34, 'title' => 'KABUPATEN SLEMAN'],
            ['id' => 3471, 'province_id' => 34, 'title' => 'KOTA YOGYAKARTA'],
            ['id' => 3501, 'province_id' => 35, 'title' => 'KABUPATEN PACITAN'],
            ['id' => 3502, 'province_id' => 35, 'title' => 'KABUPATEN PONOROGO'],
            ['id' => 3503, 'province_id' => 35, 'title' => 'KABUPATEN TRENGGALEK'],
            ['id' => 3504, 'province_id' => 35, 'title' => 'KABUPATEN TULUNGAGUNG'],
            ['id' => 3505, 'province_id' => 35, 'title' => 'KABUPATEN BLITAR'],
            ['id' => 3506, 'province_id' => 35, 'title' => 'KABUPATEN KEDIRI'],
            ['id' => 3507, 'province_id' => 35, 'title' => 'KABUPATEN MALANG'],
            ['id' => 3508, 'province_id' => 35, 'title' => 'KABUPATEN LUMAJANG'],
            ['id' => 3509, 'province_id' => 35, 'title' => 'KABUPATEN JEMBER'],
            ['id' => 3510, 'province_id' => 35, 'title' => 'KABUPATEN BANYUWANGI'],
            ['id' => 3511, 'province_id' => 35, 'title' => 'KABUPATEN BONDOWOSO'],
            ['id' => 3512, 'province_id' => 35, 'title' => 'KABUPATEN SITUBONDO'],
            ['id' => 3513, 'province_id' => 35, 'title' => 'KABUPATEN PROBOLINGGO'],
            ['id' => 3514, 'province_id' => 35, 'title' => 'KABUPATEN PASURUAN'],
            ['id' => 3515, 'province_id' => 35, 'title' => 'KABUPATEN SIDOARJO'],
            ['id' => 3516, 'province_id' => 35, 'title' => 'KABUPATEN MOJOKERTO'],
            ['id' => 3517, 'province_id' => 35, 'title' => 'KABUPATEN JOMBANG'],
            ['id' => 3518, 'province_id' => 35, 'title' => 'KABUPATEN NGANJUK'],
            ['id' => 3519, 'province_id' => 35, 'title' => 'KABUPATEN MADIUN'],
            ['id' => 3520, 'province_id' => 35, 'title' => 'KABUPATEN MAGETAN'],
            ['id' => 3521, 'province_id' => 35, 'title' => 'KABUPATEN NGAWI'],
            ['id' => 3522, 'province_id' => 35, 'title' => 'KABUPATEN BOJONEGORO'],
            ['id' => 3523, 'province_id' => 35, 'title' => 'KABUPATEN TUBAN'],
            ['id' => 3524, 'province_id' => 35, 'title' => 'KABUPATEN LAMONGAN'],
            ['id' => 3525, 'province_id' => 35, 'title' => 'KABUPATEN GRESIK'],
            ['id' => 3526, 'province_id' => 35, 'title' => 'KABUPATEN BANGKALAN'],
            ['id' => 3527, 'province_id' => 35, 'title' => 'KABUPATEN SAMPANG'],
            ['id' => 3528, 'province_id' => 35, 'title' => 'KABUPATEN PAMEKASAN'],
            ['id' => 3529, 'province_id' => 35, 'title' => 'KABUPATEN SUMENEP'],
            ['id' => 3571, 'province_id' => 35, 'title' => 'KOTA KEDIRI'],
            ['id' => 3572, 'province_id' => 35, 'title' => 'KOTA BLITAR'],
            ['id' => 3573, 'province_id' => 35, 'title' => 'KOTA MALANG'],
            ['id' => 3574, 'province_id' => 35, 'title' => 'KOTA PROBOLINGGO'],
            ['id' => 3575, 'province_id' => 35, 'title' => 'KOTA PASURUAN'],
            ['id' => 3576, 'province_id' => 35, 'title' => 'KOTA MOJOKERTO'],
            ['id' => 3577, 'province_id' => 35, 'title' => 'KOTA MADIUN'],
            ['id' => 3578, 'province_id' => 35, 'title' => 'KOTA SURABAYA'],
            ['id' => 3579, 'province_id' => 35, 'title' => 'KOTA BATU'],
            ['id' => 3601, 'province_id' => 36, 'title' => 'KABUPATEN PANDEGLANG'],
            ['id' => 3602, 'province_id' => 36, 'title' => 'KABUPATEN LEBAK'],
            ['id' => 3603, 'province_id' => 36, 'title' => 'KABUPATEN TANGERANG'],
            ['id' => 3604, 'province_id' => 36, 'title' => 'KABUPATEN SERANG'],
            ['id' => 3671, 'province_id' => 36, 'title' => 'KOTA TANGERANG'],
            ['id' => 3672, 'province_id' => 36, 'title' => 'KOTA CILEGON'],
            ['id' => 3673, 'province_id' => 36, 'title' => 'KOTA SERANG'],
            ['id' => 3674, 'province_id' => 36, 'title' => 'KOTA TANGERANG SELATAN'],
            ['id' => 5101, 'province_id' => 51, 'title' => 'KABUPATEN JEMBRANA'],
            ['id' => 5102, 'province_id' => 51, 'title' => 'KABUPATEN TABANAN'],
            ['id' => 5103, 'province_id' => 51, 'title' => 'KABUPATEN BADUNG'],
            ['id' => 5104, 'province_id' => 51, 'title' => 'KABUPATEN GIANYAR'],
            ['id' => 5105, 'province_id' => 51, 'title' => 'KABUPATEN KLUNGKUNG'],
            ['id' => 5106, 'province_id' => 51, 'title' => 'KABUPATEN BANGLI'],
            ['id' => 5107, 'province_id' => 51, 'title' => 'KABUPATEN KARANG ASEM'],
            ['id' => 5108, 'province_id' => 51, 'title' => 'KABUPATEN BULELENG'],
            ['id' => 5171, 'province_id' => 51, 'title' => 'KOTA DENPASAR'],
            ['id' => 5201, 'province_id' => 52, 'title' => 'KABUPATEN LOMBOK BARAT'],
            ['id' => 5202, 'province_id' => 52, 'title' => 'KABUPATEN LOMBOK TENGAH'],
            ['id' => 5203, 'province_id' => 52, 'title' => 'KABUPATEN LOMBOK TIMUR'],
            ['id' => 5204, 'province_id' => 52, 'title' => 'KABUPATEN SUMBAWA'],
            ['id' => 5205, 'province_id' => 52, 'title' => 'KABUPATEN DOMPU'],
            ['id' => 5206, 'province_id' => 52, 'title' => 'KABUPATEN BIMA'],
            ['id' => 5207, 'province_id' => 52, 'title' => 'KABUPATEN SUMBAWA BARAT'],
            ['id' => 5208, 'province_id' => 52, 'title' => 'KABUPATEN LOMBOK UTARA'],
            ['id' => 5271, 'province_id' => 52, 'title' => 'KOTA MATARAM'],
            ['id' => 5272, 'province_id' => 52, 'title' => 'KOTA BIMA'],
            ['id' => 5301, 'province_id' => 53, 'title' => 'KABUPATEN SUMBA BARAT'],
            ['id' => 5302, 'province_id' => 53, 'title' => 'KABUPATEN SUMBA TIMUR'],
            ['id' => 5303, 'province_id' => 53, 'title' => 'KABUPATEN KUPANG'],
            ['id' => 5304, 'province_id' => 53, 'title' => 'KABUPATEN TIMOR TENGAH SELATAN'],
            ['id' => 5305, 'province_id' => 53, 'title' => 'KABUPATEN TIMOR TENGAH UTARA'],
            ['id' => 5306, 'province_id' => 53, 'title' => 'KABUPATEN BELU'],
            ['id' => 5307, 'province_id' => 53, 'title' => 'KABUPATEN ALOR'],
            ['id' => 5308, 'province_id' => 53, 'title' => 'KABUPATEN LEMBATA'],
            ['id' => 5309, 'province_id' => 53, 'title' => 'KABUPATEN FLORES TIMUR'],
            ['id' => 5310, 'province_id' => 53, 'title' => 'KABUPATEN SIKKA'],
            ['id' => 5311, 'province_id' => 53, 'title' => 'KABUPATEN ENDE'],
            ['id' => 5312, 'province_id' => 53, 'title' => 'KABUPATEN NGADA'],
            ['id' => 5313, 'province_id' => 53, 'title' => 'KABUPATEN MANGGARAI'],
            ['id' => 5314, 'province_id' => 53, 'title' => 'KABUPATEN ROTE NDAO'],
            ['id' => 5315, 'province_id' => 53, 'title' => 'KABUPATEN MANGGARAI BARAT'],
            ['id' => 5316, 'province_id' => 53, 'title' => 'KABUPATEN SUMBA TENGAH'],
            ['id' => 5317, 'province_id' => 53, 'title' => 'KABUPATEN SUMBA BARAT DAYA'],
            ['id' => 5318, 'province_id' => 53, 'title' => 'KABUPATEN NAGEKEO'],
            ['id' => 5319, 'province_id' => 53, 'title' => 'KABUPATEN MANGGARAI TIMUR'],
            ['id' => 5320, 'province_id' => 53, 'title' => 'KABUPATEN SABU RAIJUA'],
            ['id' => 5321, 'province_id' => 53, 'title' => 'KABUPATEN MALAKA'],
            ['id' => 5371, 'province_id' => 53, 'title' => 'KOTA KUPANG'],
            ['id' => 6101, 'province_id' => 61, 'title' => 'KABUPATEN SAMBAS'],
            ['id' => 6102, 'province_id' => 61, 'title' => 'KABUPATEN BENGKAYANG'],
            ['id' => 6103, 'province_id' => 61, 'title' => 'KABUPATEN LANDAK'],
            ['id' => 6104, 'province_id' => 61, 'title' => 'KABUPATEN MEMPAWAH'],
            ['id' => 6105, 'province_id' => 61, 'title' => 'KABUPATEN SANGGAU'],
            ['id' => 6106, 'province_id' => 61, 'title' => 'KABUPATEN KETAPANG'],
            ['id' => 6107, 'province_id' => 61, 'title' => 'KABUPATEN SINTANG'],
            ['id' => 6108, 'province_id' => 61, 'title' => 'KABUPATEN KAPUAS HULU'],
            ['id' => 6109, 'province_id' => 61, 'title' => 'KABUPATEN SEKADAU'],
            ['id' => 6110, 'province_id' => 61, 'title' => 'KABUPATEN MELAWI'],
            ['id' => 6111, 'province_id' => 61, 'title' => 'KABUPATEN KAYONG UTARA'],
            ['id' => 6112, 'province_id' => 61, 'title' => 'KABUPATEN KUBU RAYA'],
            ['id' => 6171, 'province_id' => 61, 'title' => 'KOTA PONTIANAK'],
            ['id' => 6172, 'province_id' => 61, 'title' => 'KOTA SINGKAWANG'],
            ['id' => 6201, 'province_id' => 62, 'title' => 'KABUPATEN KOTAWARINGIN BARAT'],
            ['id' => 6202, 'province_id' => 62, 'title' => 'KABUPATEN KOTAWARINGIN TIMUR'],
            ['id' => 6203, 'province_id' => 62, 'title' => 'KABUPATEN KAPUAS'],
            ['id' => 6204, 'province_id' => 62, 'title' => 'KABUPATEN BARITO SELATAN'],
            ['id' => 6205, 'province_id' => 62, 'title' => 'KABUPATEN BARITO UTARA'],
            ['id' => 6206, 'province_id' => 62, 'title' => 'KABUPATEN SUKAMARA'],
            ['id' => 6207, 'province_id' => 62, 'title' => 'KABUPATEN LAMANDAU'],
            ['id' => 6208, 'province_id' => 62, 'title' => 'KABUPATEN SERUYAN'],
            ['id' => 6209, 'province_id' => 62, 'title' => 'KABUPATEN KATINGAN'],
            ['id' => 6210, 'province_id' => 62, 'title' => 'KABUPATEN PULANG PISAU'],
            ['id' => 6211, 'province_id' => 62, 'title' => 'KABUPATEN GUNUNG MAS'],
            ['id' => 6212, 'province_id' => 62, 'title' => 'KABUPATEN BARITO TIMUR'],
            ['id' => 6213, 'province_id' => 62, 'title' => 'KABUPATEN MURUNG RAYA'],
            ['id' => 6271, 'province_id' => 62, 'title' => 'KOTA PALANGKA RAYA'],
            ['id' => 6301, 'province_id' => 63, 'title' => 'KABUPATEN TANAH LAUT'],
            ['id' => 6302, 'province_id' => 63, 'title' => 'KABUPATEN KOTA BARU'],
            ['id' => 6303, 'province_id' => 63, 'title' => 'KABUPATEN BANJAR'],
            ['id' => 6304, 'province_id' => 63, 'title' => 'KABUPATEN BARITO KUALA'],
            ['id' => 6305, 'province_id' => 63, 'title' => 'KABUPATEN TAPIN'],
            ['id' => 6306, 'province_id' => 63, 'title' => 'KABUPATEN HULU SUNGAI SELATAN'],
            ['id' => 6307, 'province_id' => 63, 'title' => 'KABUPATEN HULU SUNGAI TENGAH'],
            ['id' => 6308, 'province_id' => 63, 'title' => 'KABUPATEN HULU SUNGAI UTARA'],
            ['id' => 6309, 'province_id' => 63, 'title' => 'KABUPATEN TABALONG'],
            ['id' => 6310, 'province_id' => 63, 'title' => 'KABUPATEN TANAH BUMBU'],
            ['id' => 6311, 'province_id' => 63, 'title' => 'KABUPATEN BALANGAN'],
            ['id' => 6371, 'province_id' => 63, 'title' => 'KOTA BANJARMASIN'],
            ['id' => 6372, 'province_id' => 63, 'title' => 'KOTA BANJAR BARU'],
            ['id' => 6401, 'province_id' => 64, 'title' => 'KABUPATEN PASER'],
            ['id' => 6402, 'province_id' => 64, 'title' => 'KABUPATEN KUTAI BARAT'],
            ['id' => 6403, 'province_id' => 64, 'title' => 'KABUPATEN KUTAI KARTANEGARA'],
            ['id' => 6404, 'province_id' => 64, 'title' => 'KABUPATEN KUTAI TIMUR'],
            ['id' => 6405, 'province_id' => 64, 'title' => 'KABUPATEN BERAU'],
            ['id' => 6409, 'province_id' => 64, 'title' => 'KABUPATEN PENAJAM PASER UTARA'],
            ['id' => 6411, 'province_id' => 64, 'title' => 'KABUPATEN MAHAKAM HULU'],
            ['id' => 6471, 'province_id' => 64, 'title' => 'KOTA BALIKPAPAN'],
            ['id' => 6472, 'province_id' => 64, 'title' => 'KOTA SAMARINDA'],
            ['id' => 6474, 'province_id' => 64, 'title' => 'KOTA BONTANG'],
            ['id' => 6501, 'province_id' => 65, 'title' => 'KABUPATEN MALINAU'],
            ['id' => 6502, 'province_id' => 65, 'title' => 'KABUPATEN BULUNGAN'],
            ['id' => 6503, 'province_id' => 65, 'title' => 'KABUPATEN TANA TIDUNG'],
            ['id' => 6504, 'province_id' => 65, 'title' => 'KABUPATEN NUNUKAN'],
            ['id' => 6571, 'province_id' => 65, 'title' => 'KOTA TARAKAN'],
            ['id' => 7101, 'province_id' => 71, 'title' => 'KABUPATEN BOLAANG MONGONDOW'],
            ['id' => 7102, 'province_id' => 71, 'title' => 'KABUPATEN MINAHASA'],
            ['id' => 7103, 'province_id' => 71, 'title' => 'KABUPATEN KEPULAUAN SANGIHE'],
            ['id' => 7104, 'province_id' => 71, 'title' => 'KABUPATEN KEPULAUAN TALAUD'],
            ['id' => 7105, 'province_id' => 71, 'title' => 'KABUPATEN MINAHASA SELATAN'],
            ['id' => 7106, 'province_id' => 71, 'title' => 'KABUPATEN MINAHASA UTARA'],
            ['id' => 7107, 'province_id' => 71, 'title' => 'KABUPATEN BOLAANG MONGONDOW UTARA'],
            ['id' => 7108, 'province_id' => 71, 'title' => 'KABUPATEN SIAU TAGULANDANG BIARO'],
            ['id' => 7109, 'province_id' => 71, 'title' => 'KABUPATEN MINAHASA TENGGARA'],
            ['id' => 7110, 'province_id' => 71, 'title' => 'KABUPATEN BOLAANG MONGONDOW SELATAN'],
            ['id' => 7111, 'province_id' => 71, 'title' => 'KABUPATEN BOLAANG MONGONDOW TIMUR'],
            ['id' => 7171, 'province_id' => 71, 'title' => 'KOTA MANADO'],
            ['id' => 7172, 'province_id' => 71, 'title' => 'KOTA BITUNG'],
            ['id' => 7173, 'province_id' => 71, 'title' => 'KOTA TOMOHON'],
            ['id' => 7174, 'province_id' => 71, 'title' => 'KOTA KOTAMOBAGU'],
            ['id' => 7201, 'province_id' => 72, 'title' => 'KABUPATEN BANGGAI KEPULAUAN'],
            ['id' => 7202, 'province_id' => 72, 'title' => 'KABUPATEN BANGGAI'],
            ['id' => 7203, 'province_id' => 72, 'title' => 'KABUPATEN MOROWALI'],
            ['id' => 7204, 'province_id' => 72, 'title' => 'KABUPATEN POSO'],
            ['id' => 7205, 'province_id' => 72, 'title' => 'KABUPATEN DONGGALA'],
            ['id' => 7206, 'province_id' => 72, 'title' => 'KABUPATEN TOLI-TOLI'],
            ['id' => 7207, 'province_id' => 72, 'title' => 'KABUPATEN BUOL'],
            ['id' => 7208, 'province_id' => 72, 'title' => 'KABUPATEN PARIGI MOUTONG'],
            ['id' => 7209, 'province_id' => 72, 'title' => 'KABUPATEN TOJO UNA-UNA'],
            ['id' => 7210, 'province_id' => 72, 'title' => 'KABUPATEN SIGI'],
            ['id' => 7211, 'province_id' => 72, 'title' => 'KABUPATEN BANGGAI LAUT'],
            ['id' => 7212, 'province_id' => 72, 'title' => 'KABUPATEN MOROWALI UTARA'],
            ['id' => 7271, 'province_id' => 72, 'title' => 'KOTA PALU'],
            ['id' => 7301, 'province_id' => 73, 'title' => 'KABUPATEN KEPULAUAN SELAYAR'],
            ['id' => 7302, 'province_id' => 73, 'title' => 'KABUPATEN BULUKUMBA'],
            ['id' => 7303, 'province_id' => 73, 'title' => 'KABUPATEN BANTAENG'],
            ['id' => 7304, 'province_id' => 73, 'title' => 'KABUPATEN JENEPONTO'],
            ['id' => 7305, 'province_id' => 73, 'title' => 'KABUPATEN TAKALAR'],
            ['id' => 7306, 'province_id' => 73, 'title' => 'KABUPATEN GOWA'],
            ['id' => 7307, 'province_id' => 73, 'title' => 'KABUPATEN SINJAI'],
            ['id' => 7308, 'province_id' => 73, 'title' => 'KABUPATEN MAROS'],
            ['id' => 7309, 'province_id' => 73, 'title' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN'],
            ['id' => 7310, 'province_id' => 73, 'title' => 'KABUPATEN BARRU'],
            ['id' => 7311, 'province_id' => 73, 'title' => 'KABUPATEN BONE'],
            ['id' => 7312, 'province_id' => 73, 'title' => 'KABUPATEN SOPPENG'],
            ['id' => 7313, 'province_id' => 73, 'title' => 'KABUPATEN WAJO'],
            ['id' => 7314, 'province_id' => 73, 'title' => 'KABUPATEN SIDENRENG RAPPANG'],
            ['id' => 7315, 'province_id' => 73, 'title' => 'KABUPATEN PINRANG'],
            ['id' => 7316, 'province_id' => 73, 'title' => 'KABUPATEN ENREKANG'],
            ['id' => 7317, 'province_id' => 73, 'title' => 'KABUPATEN LUWU'],
            ['id' => 7318, 'province_id' => 73, 'title' => 'KABUPATEN TANA TORAJA'],
            ['id' => 7322, 'province_id' => 73, 'title' => 'KABUPATEN LUWU UTARA'],
            ['id' => 7325, 'province_id' => 73, 'title' => 'KABUPATEN LUWU TIMUR'],
            ['id' => 7326, 'province_id' => 73, 'title' => 'KABUPATEN TORAJA UTARA'],
            ['id' => 7371, 'province_id' => 73, 'title' => 'KOTA MAKASSAR'],
            ['id' => 7372, 'province_id' => 73, 'title' => 'KOTA PARE-PARE'],
            ['id' => 7373, 'province_id' => 73, 'title' => 'KOTA PALOPO'],
            ['id' => 7401, 'province_id' => 74, 'title' => 'KABUPATEN BUTON'],
            ['id' => 7402, 'province_id' => 74, 'title' => 'KABUPATEN MUNA'],
            ['id' => 7403, 'province_id' => 74, 'title' => 'KABUPATEN KONAWE'],
            ['id' => 7404, 'province_id' => 74, 'title' => 'KABUPATEN KOLAKA'],
            ['id' => 7405, 'province_id' => 74, 'title' => 'KABUPATEN KONAWE SELATAN'],
            ['id' => 7406, 'province_id' => 74, 'title' => 'KABUPATEN BOMBANA'],
            ['id' => 7407, 'province_id' => 74, 'title' => 'KABUPATEN WAKATOBI'],
            ['id' => 7408, 'province_id' => 74, 'title' => 'KABUPATEN KOLAKA UTARA'],
            ['id' => 7409, 'province_id' => 74, 'title' => 'KABUPATEN BUTON UTARA'],
            ['id' => 7410, 'province_id' => 74, 'title' => 'KABUPATEN KONAWE UTARA'],
            ['id' => 7411, 'province_id' => 74, 'title' => 'KABUPATEN KOLAKA TIMUR'],
            ['id' => 7412, 'province_id' => 74, 'title' => 'KABUPATEN KONAWE KEPULAUAN'],
            ['id' => 7413, 'province_id' => 74, 'title' => 'KABUPATEN MUNA BARAT'],
            ['id' => 7414, 'province_id' => 74, 'title' => 'KABUPATEN BUTON TENGAH'],
            ['id' => 7415, 'province_id' => 74, 'title' => 'KABUPATEN BUTON SELATAN'],
            ['id' => 7471, 'province_id' => 74, 'title' => 'KOTA KENDARI'],
            ['id' => 7472, 'province_id' => 74, 'title' => 'KOTA BAUBAU'],
            ['id' => 7501, 'province_id' => 75, 'title' => 'KABUPATEN BOALEMO'],
            ['id' => 7502, 'province_id' => 75, 'title' => 'KABUPATEN GORONTALO'],
            ['id' => 7503, 'province_id' => 75, 'title' => 'KABUPATEN POHUWATO'],
            ['id' => 7504, 'province_id' => 75, 'title' => 'KABUPATEN BONE BOLANGO'],
            ['id' => 7505, 'province_id' => 75, 'title' => 'KABUPATEN GORONTALO UTARA'],
            ['id' => 7571, 'province_id' => 75, 'title' => 'KOTA GORONTALO'],
            ['id' => 7601, 'province_id' => 76, 'title' => 'KABUPATEN MAJENE'],
            ['id' => 7602, 'province_id' => 76, 'title' => 'KABUPATEN POLEWALI MANDAR'],
            ['id' => 7603, 'province_id' => 76, 'title' => 'KABUPATEN MAMASA'],
            ['id' => 7604, 'province_id' => 76, 'title' => 'KABUPATEN MAMUJU'],
            ['id' => 7605, 'province_id' => 76, 'title' => 'KABUPATEN MAMUJU UTARA'],
            ['id' => 7606, 'province_id' => 76, 'title' => 'KABUPATEN MAMUJU TENGAH'],
            ['id' => 8101, 'province_id' => 81, 'title' => 'KABUPATEN MALUKU TENGGARA BARAT'],
            ['id' => 8102, 'province_id' => 81, 'title' => 'KABUPATEN MALUKU TENGGARA'],
            ['id' => 8103, 'province_id' => 81, 'title' => 'KABUPATEN MALUKU TENGAH'],
            ['id' => 8104, 'province_id' => 81, 'title' => 'KABUPATEN BURU'],
            ['id' => 8105, 'province_id' => 81, 'title' => 'KABUPATEN KEPULAUAN ARU'],
            ['id' => 8106, 'province_id' => 81, 'title' => 'KABUPATEN SERAM BAGIAN BARAT'],
            ['id' => 8107, 'province_id' => 81, 'title' => 'KABUPATEN SERAM BAGIAN TIMUR'],
            ['id' => 8108, 'province_id' => 81, 'title' => 'KABUPATEN MALUKU BARAT DAYA'],
            ['id' => 8109, 'province_id' => 81, 'title' => 'KABUPATEN BURU SELATAN'],
            ['id' => 8171, 'province_id' => 81, 'title' => 'KOTA AMBON'],
            ['id' => 8172, 'province_id' => 81, 'title' => 'KOTA TUAL'],
            ['id' => 8201, 'province_id' => 82, 'title' => 'KABUPATEN HALMAHERA BARAT'],
            ['id' => 8202, 'province_id' => 82, 'title' => 'KABUPATEN HALMAHERA TENGAH'],
            ['id' => 8203, 'province_id' => 82, 'title' => 'KABUPATEN KEPULAUAN SULA'],
            ['id' => 8204, 'province_id' => 82, 'title' => 'KABUPATEN HALMAHERA SELATAN'],
            ['id' => 8205, 'province_id' => 82, 'title' => 'KABUPATEN HALMAHERA UTARA'],
            ['id' => 8206, 'province_id' => 82, 'title' => 'KABUPATEN HALMAHERA TIMUR'],
            ['id' => 8207, 'province_id' => 82, 'title' => 'KABUPATEN PULAU MOROTAI'],
            ['id' => 8208, 'province_id' => 82, 'title' => 'KABUPATEN PULAU TALIABU'],
            ['id' => 8271, 'province_id' => 82, 'title' => 'KOTA TERNATE'],
            ['id' => 8272, 'province_id' => 82, 'title' => 'KOTA TIDORE KEPULAUAN'],
            ['id' => 9101, 'province_id' => 91, 'title' => 'KABUPATEN FAK-FAK'],
            ['id' => 9102, 'province_id' => 91, 'title' => 'KABUPATEN KAIMANA'],
            ['id' => 9103, 'province_id' => 91, 'title' => 'KABUPATEN TELUK WONDAMA'],
            ['id' => 9104, 'province_id' => 91, 'title' => 'KABUPATEN TELUK BINTUNI'],
            ['id' => 9105, 'province_id' => 91, 'title' => 'KABUPATEN MANOKWARI'],
            ['id' => 9106, 'province_id' => 91, 'title' => 'KABUPATEN SORONG SELATAN'],
            ['id' => 9107, 'province_id' => 91, 'title' => 'KABUPATEN SORONG'],
            ['id' => 9108, 'province_id' => 91, 'title' => 'KABUPATEN RAJA AMPAT'],
            ['id' => 9109, 'province_id' => 91, 'title' => 'KABUPATEN TAMBRAUW'],
            ['id' => 9110, 'province_id' => 91, 'title' => 'KABUPATEN MAYBRAT'],
            ['id' => 9111, 'province_id' => 91, 'title' => 'KABUPATEN MANOKWARI SELATAN'],
            ['id' => 9112, 'province_id' => 91, 'title' => 'KABUPATEN PEGUNUNGAN ARFAK'],
            ['id' => 9171, 'province_id' => 91, 'title' => 'KOTA SORONG'],
            ['id' => 9401, 'province_id' => 94, 'title' => 'KABUPATEN MERAUKE'],
            ['id' => 9402, 'province_id' => 94, 'title' => 'KABUPATEN JAYAWIJAYA'],
            ['id' => 9403, 'province_id' => 94, 'title' => 'KABUPATEN JAYAPURA'],
            ['id' => 9404, 'province_id' => 94, 'title' => 'KABUPATEN NABIRE'],
            ['id' => 9408, 'province_id' => 94, 'title' => 'KABUPATEN KEPULAUAN YAPEN'],
            ['id' => 9409, 'province_id' => 94, 'title' => 'KABUPATEN BIAK NUMFOR'],
            ['id' => 9410, 'province_id' => 94, 'title' => 'KABUPATEN PANIAI'],
            ['id' => 9411, 'province_id' => 94, 'title' => 'KABUPATEN PUNCAK JAYA'],
            ['id' => 9412, 'province_id' => 94, 'title' => 'KABUPATEN MIMIKA'],
            ['id' => 9413, 'province_id' => 94, 'title' => 'KABUPATEN BOVEN DIGOEL'],
            ['id' => 9414, 'province_id' => 94, 'title' => 'KABUPATEN MAPPI'],
            ['id' => 9415, 'province_id' => 94, 'title' => 'KABUPATEN ASMAT'],
            ['id' => 9416, 'province_id' => 94, 'title' => 'KABUPATEN YAHUKIMO'],
            ['id' => 9417, 'province_id' => 94, 'title' => 'KABUPATEN PEGUNUNGAN BINTANG'],
            ['id' => 9418, 'province_id' => 94, 'title' => 'KABUPATEN TOLIKARA'],
            ['id' => 9419, 'province_id' => 94, 'title' => 'KABUPATEN SARMI'],
            ['id' => 9420, 'province_id' => 94, 'title' => 'KABUPATEN KEEROM'],
            ['id' => 9426, 'province_id' => 94, 'title' => 'KABUPATEN WAROPEN'],
            ['id' => 9427, 'province_id' => 94, 'title' => 'KABUPATEN SUPIORI'],
            ['id' => 9428, 'province_id' => 94, 'title' => 'KABUPATEN MAMBERAMO RAYA'],
            ['id' => 9429, 'province_id' => 94, 'title' => 'KABUPATEN NDUGA'],
            ['id' => 9430, 'province_id' => 94, 'title' => 'KABUPATEN LANNY JAYA'],
            ['id' => 9431, 'province_id' => 94, 'title' => 'KABUPATEN MAMBERAMO TENGAH'],
            ['id' => 9432, 'province_id' => 94, 'title' => 'KABUPATEN YALIMO'],
            ['id' => 9433, 'province_id' => 94, 'title' => 'KABUPATEN PUNCAK'],
            ['id' => 9434, 'province_id' => 94, 'title' => 'KABUPATEN DOGIYAI'],
            ['id' => 9435, 'province_id' => 94, 'title' => 'KABUPATEN INTAN JAYA'],
            ['id' => 9436, 'province_id' => 94, 'title' => 'KABUPATEN DEIYAI'],
            ['id' => 9471, 'province_id' => 94, 'title' => 'KOTA JAYAPURA'],
        ];

        foreach ($cities as $city) {
            DB::table('cities')->insert([
                'id' => $city['id'],
                'province_id' => $city['province_id'],
                'city_id' => $city['id'], // Adding city_id
                'title' => $city['title'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
                
        }
    }
}
